package com.kgisl.nsure.dbconstants;

public class AuthSQL {
	
	public static String updateInvalidAccessCount = "UPDATE EIS_MST_LOGIN_ACCESS SET NUM_INVALID_ACCESS_COUNT = ? WHERE VCH_LOGIN_NAME = ?";
	
	public static String updateAccountLock = "UPDATE EIS_MST_LOGIN_ACCESS SET CHR_LOCKED = ? WHERE VCH_LOGIN_NAME = ?";
	
	public static String getInvalidAccessCount = "SELECT NUM_INVALID_ACCESS_COUNT FROM EIS_MST_LOGIN_ACCESS WHERE VCH_LOGIN_NAME = ?";
	
	public static String getMaxLoginAttempt = "SELECT NUM_UNSUCESS_LOGIN_ATTEMPTS FROM (SELECT NUM_UNSUCESS_LOGIN_ATTEMPTS FROM EIS_MST_SYSTEM_CONFIG ORDER BY DTT_CREATION_DATE DESC) WHERE ROWNUM=1";
	
	public static String saveLoginHistory = "INSERT INTO EIS_TRN_LOGIN_HISTORY (NUM_LOGIN_ID,DTT_LOGIN_TIME,VCH_SESSION_ID,CHR_LOGIN_TYPE,DTT_CREATION_DATE) VALUES (?,SYSDATE,?,?,SYSDATE)";
	
	public static String updateLoginHistory = "UPDATE EIS_TRN_LOGIN_HISTORY SET DTT_LOGOUT_TIME = SYSDATE WHERE VCH_SESSION_ID = ? AND NUM_LOGIN_ID = ?";
	
	public static String getSessionId = "SELECT VCH_SESSION_ID FROM EIS_TRN_LOGIN_HISTORY WHERE NUM_LOGIN_ID = ? AND DTT_LOGOUT_TIME IS NULL";
	
	public static String saveLoginAttempt = "INSERT INTO EIS_TRN_LOGIN_ATTEMPT (NUM_LOGIN_ID, VCH_LOGIN_NAME, CHR_LOGIN_TYPE, DTT_LOGIN_ATTEMPT_TIME, VCH_LOGIN_ROLE ) VALUES (?, ?, ?, sysdate, ?)";
	
	public static String getUserDetails = "SELECT NUM_LOGIN_ID, VCH_PASSWORD_KEY, VCH_PASSWORD, CHR_ALLOW_MULTIPLE_SESSION FROM EIS_MST_LOGIN_ACCESS WHERE VCH_LOGIN_NAME = ?";
	
	public static String getPreviousLoggedUser = "SELECT COUNT(NUM_LOGIN_HISTORY_ID) AS V_CURRENT_LOGIN_CNT FROM EIS_TRN_LOGIN_HISTORY WHERE DTT_LOGOUT_TIME IS NULL AND NUM_LOGIN_ID = ? AND VCH_SESSION_ID!= ?";
	
	public static String getPreviousLoggedUserSessionId = "SELECT VCH_SESSION_ID FROM EIS_TRN_LOGIN_HISTORY WHERE DTT_LOGOUT_TIME IS NULL AND NUM_LOGIN_ID = ? AND VCH_SESSION_ID!= ?";
	
	public static String cleanupLoginHistory = "UPDATE EIS_TRN_LOGIN_HISTORY SET DTT_LOGOUT_TIME = SYSDATE WHERE VCH_SESSION_ID != ? AND NUM_LOGIN_ID = ?";

	public static final StringBuilder VALIDATE_AUTHORISED_ROLE = new StringBuilder("SELECT NUM_ROLE_ID FROM (SELECT COUNT(NVL(ROLE.NUM_ROLE_ID,0)) AS NUM_ROLE_ID")
	.append(" FROM EIS_MST_MENU MENU,EIS_MST_LOGIN_ROLE ROLE,EIS_MST_ROLE_MENU ROLEMENU ")
	.append(" WHERE ROLEMENU.NUM_MENU_ID = MENU.NUM_MENU_ID")
	.append(" AND ROLE.NUM_ROLE_ID = ROLEMENU.NUM_ROLE_ID")
	.append(" AND ROLEMENU.CHR_ACTIVE = 'Y' AND MENU.CHR_ACTIVE_STATUS = 'Y' ")
	.append(" AND ROLE.NUM_LOGIN_ID = ? ### ")
	.append(" ORDER BY ROLEMENU.DTT_CREATION_DATE DESC ) FETCH FIRST 1 ROWS ONLY");

}
