/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-12-19 08:50:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\" ng-csp>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Single page web app using Angularjs</title>\n");
      out.write("<base href=\"\">\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/angular.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/angular-route.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/ngStorage.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/angular-ui-router.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/ui-grid/ui-grid.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/ui-grid/vfs_fonts.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/angular-sanitize.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main/angular-local-storage.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/ui-grid/ui-grid.min.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".myGrid {\n");
      out.write(" width: auto;\n");
      out.write(" height: 250px;\n");
      out.write(" }\n");
      out.write(" .uiGridClass:hover{\n");
      out.write(" background-color: #b3c4c7;\n");
      out.write(" }\n");
      out.write(" @charset \"UTF-8\";\n");
      out.write("\n");
      out.write("[ng\\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak],\n");
      out.write(".ng-cloak, .x-ng-cloak,\n");
      out.write(".ng-hide:not(.ng-hide-animate) {\n");
      out.write("  display: none !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ng\\:form {\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body ng-app=\"single-page-app\">\n");
      out.write("\t<div ng-controller=\"cfgController as main\">\n");
      out.write("\t\t<div ng-bind-html=\"secureHtml\"></div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<nav class=\"navbar navbar-inverse\" role=\"navigation\"\n");
      out.write("\t\t\t\tstyle=\"padding-left: 130px;\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a ui-sref=\"home\">Home<span\n");
      out.write("\t\t\t\t\t\t\tclass=\"sr-only\">(current)</span></a></li>\n");
      out.write("\t\t\t\t\t<!-- <li><a ui-sref=\"about\">About us</a></li>\n");
      out.write("\t\t\t\t\t<li><a ui-sref=\"final\">Final</a></li> -->\n");
      out.write("\t\t\t\t\t<li><a ui-sref=\"second\">Second Home</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<br />\n");
      out.write("\t\t<div ui-grid=\"gridOptions\" class=\"myGrid\" ui-grid-pagination></div>\n");
      out.write("\t\t<form id=\"signup-form\">\n");
      out.write("\t\t\t<div ui-view class=\"jumbotron\"></div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/app.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
